// app/layout.js

import "./globals.css";
import Footer from "./components/Footer";
import BettingNavbar from "./components/Navbar";

// 1. Import Poppins from next/font/google (named import)
import { Poppins } from "next/font/google";

// 2. Configure the weights/subsets you need
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={poppins.className}>
      {/* 3. Now every element inside has Poppins applied */}
      <body className="antialiased">
        <BettingNavbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
